version: '3.9'

services:

  roundcube:
    container_name: ${ROUNDCUBEMAIL_NAME}
    build:
      context: .
      args:
        TAG: ${ROUNDCUBEMAIL_TAG}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      ROUNDCUBEMAIL_DEFAULT_HOST: ${ROUNDCUBEMAIL_DEFAULT_HOST}
      ROUNDCUBEMAIL_DEFAULT_PORT: ${ROUNDCUBEMAIL_DEFAULT_PORT}
      ROUNDCUBEMAIL_SMTP_SERVER: ${ROUNDCUBEMAIL_SMTP_SERVER}
      ROUNDCUBEMAIL_SMTP_PORT: ${ROUNDCUBEMAIL_SMTP_PORT}
      ROUNDCUBEMAIL_REQUEST_PATH: ${ROUNDCUBEMAIL_REQUEST_PATH}
      ROUNDCUBEMAIL_PLUGINS: ${ROUNDCUBEMAIL_PLUGINS}
      ROUNDCUBEMAIL_SKIN: ${ROUNDCUBEMAIL_SKIN}
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: ${ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE}
      ROUNDCUBEMAIL_SPELLCHECK_URI: ${ROUNDCUBEMAIL_SPELLCHECK_URI}
      ROUNDCUBEMAIL_ASPELL_DICTS: ${ROUNDCUBEMAIL_ASPELL_DICTS}
      ROUNDCUBEMAIL_DB_TYPE: ${ROUNDCUBEMAIL_DB_TYPE}
      ROUNDCUBEMAIL_DB_HOST: ${ROUNDCUBEMAIL_DB_HOST}
      ROUNDCUBEMAIL_DB_PORT: ${ROUNDCUBEMAIL_DB_PORT}
      ROUNDCUBEMAIL_DB_USER: ${ROUNDCUBEMAIL_DB_USER}
      ROUNDCUBEMAIL_DB_PASSWORD: ${ROUNDCUBEMAIL_DB_PASSWORD}
      ROUNDCUBEMAIL_DB_NAME: ${ROUNDCUBEMAIL_DB_NAME}
